name: Run tests

on: 
    push: 
        branches: [ master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
      - name: Run Behave
        run: behave
      - name: Run Pytest
        run: pytest
